Repository Team-NEXTACT/bannabe, pull requests merged in 2025-02, with the labels that each got.

#19 Chore: Pull Request & Issue 템플릿 추가
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#17 functions생성(회원, 대여 스테이션/물품 functions 생성)
  .firebaserc
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/src/index.js
  functions/src/mainPage/getLatestNotices.js
  functions/src/mainPage/index.js
  functions/src/member/auth/login.js
  functions/src/member/auth/register.js
  functions/src/member/bookmark/deleteBookmarkedStation.js
  functions/src/member/bookmark/getBookmarkedStations.js
  functions/src/member/index.js
  functions/src/member/profile/updateNickname.js
  functions/src/member/profile/updatePassword.js
  functions/src/member/profile/updateProfileImage.js
  functions/src/member/rental/getActiveRentals.js
  functions/src/member/rental/getRentalHistory.js
  functions/src/middleware/auth.js
  functions/src/payMent/approve/approveOverduePayment.js
  functions/src/payMent/approve/approveRenewalPayment.js
  functions/src/payMent/approve/approveRentalPayment.js
  functions/src/payMent/initialize/initializeExtendPayment.js
  functions/src/payMent/initialize/initializeOverduePayment.js
  functions/src/payMent/initialize/initializePayment.js
  functions/src/rentReturnItem/index.js
  functions/src/rentReturnItem/rental/getRentalItemDetail.js
  functions/src/rentReturnItem/return/getReturnItemDetail.js
  functions/src/rentReturnItem/return/returnItem.js
  functions/src/schemas/bookmarks.js
  functions/src/schemas/index.js
  functions/src/schemas/membership_payments.js
  functions/src/schemas/notices.js
  functions/src/schemas/rental_history.js
  functions/src/schemas/rental_item_types.js
  functions/src/schemas/rental_items.js
  functions/src/schemas/rental_payments.js
  functions/src/schemas/rental_station_items.js
  functions/src/schemas/rental_stations.js
  functions/src/schemas/users.js
  functions/src/stationItem/bookmark/createBookmark.js
  functions/src/stationItem/index.js
  functions/src/stationItem/station/getNearbyStations.js
  functions/src/stationItem/station/getStationDetail.js
  functions/src/stationItem/station/getStationItems.js
  functions/src/stationItem/station/searchStations.js
  functions/src/utils/admin.js
  functions/src/utils/db.js
  functions/src/utils/eventPublisher.js
  functions/src/utils/pgService.js
Labels: feature

#20 Fix: Andorid Build 오류 수정
  .gitignore
  android/app/build.gradle
  android/gradle.properties
  pubspec.lock
Labels: fix

#22 Fix: QR 스캔 패키지 교체 및 Provider 스코프 문제 해결
  lib/core/widgets/bottom_navigation_bar.dart
  lib/features/auth/views/login_view.dart
  lib/features/mypage/views/mypage_view.dart
  lib/features/rental/viewmodels/qr_scan_viewmodel.dart
  lib/features/rental/views/qr_scan_view.dart
  lib/features/rental/views/rental_status_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: fix

#23 Feature: 홈 화면 이벤트 배너 추가 및 디자인 수정
  assets/images/pc_smartphone_battery_juuden.png
  assets/images/smartphone_couple.png
  assets/images/smartphone_qr_code_man.png
  lib/features/home/views/home_view.dart
Labels: feature

#24 Feature: 회원정보 페이지 개선 및 대여 내역 분리
  lib/data/models/rental.dart
  lib/data/repositories/rental_repository.dart
  lib/features/mypage/views/edit_profile_view.dart
  lib/features/mypage/views/mypage_view.dart
  lib/features/rental/views/active_rentals_view.dart
  lib/features/rental/views/rental_history_view.dart
Labels: feature

#25 Feature: Station 모델 수정 및 지도뷰 정보 추가
  lib/core/widgets/map_view.dart
  lib/data/models/station.dart
  lib/data/repositories/station_repository.dart
  lib/features/map/viewmodels/map_viewmodel.dart
  lib/features/map/views/map_view.dart
  lib/features/rental/viewmodels/qr_scan_viewmodel.dart
  lib/features/rental/views/rental_detail_view.dart
Labels: feature

#35 Refactor: PR 알림 workflow 수정
  .github/workflows/pr-events-slack.yml
Labels: bug

#37 Chore: Slack Alert Workflow 활성화
  .github/workflows/pr-events-slack.yml
Labels: chore
